language: python
python:
  - "2.7"
os:
  - linux
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/f152ed6f566b9c9373ac
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
script: 
  - mv 8varinterpreter.py 8var
  - python 8var travis-ci-test.8v
  - python 8var -c "8v.1.0v.out'Hello'fin"
